name: Build DIE-engine (Alpine)

on:
  workflow_dispatch:

jobs:
  build-alpine:
    runs-on: ubuntu-latest

    container:
      image: alpine:latest

    steps:
      - name: Install dependencies
        run: |
          apk update
          apk add \
            alpine-sdk \
            bash \
            doas \
            git \
            cmake \
            pkgconf \
            qt5-qtbase-dev \
            qt5-qtscript-dev \
            qt5-qttools-dev \
            qt5-qtsvg-dev

      - name: Clone DIE-engine
        run: |
          git clone --recursive \
            https://github.com/horsicq/DIE-engine.git \
            /opt/DIE-engine

      - name: Build DIE-engine
        run: |
          cd /opt/DIE-engine

          pwd
          uname -m
          ls -la

          cmake \
            -S . \
            -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/usr

          cmake --build build -j$(nproc)

      - name: Build Alpine APK
        run: |
          cd /opt/DIE-engine

          mkdir -p /github/home/.abuild

          if [ ! -f /github/home/.abuild/abuild.conf ]; then
            abuild-keygen -n
            cp /github/home/.abuild/*.rsa.pub /etc/apk/keys/
          fi

          chmod a+x build_alpinepkg.sh

          bash -x build_alpinepkg.sh

      - name: Verify APK
        run: |
          mkdir -p release

          find /opt/DIE-engine \
            -name "*.apk" \
            -exec cp {} release/DetectItEasy-alpine.apk \;

          ls -lah release

          test -f release/DetectItEasy-alpine.apk

      - name: Upload Release APK
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v3
        with:
          tag_name: Beta
          draft: false
          prerelease: true
          files: |
            release/*.apk