name: Build DIE-engine (Alpine)

on:
  workflow_dispatch:

jobs:
  build-alpine:
    runs-on: ubuntu-latest
    container: alpine:latest

    steps:
      - name: Install dependencies
        run: |
          apk update
          apk add \
            qt5-qtbase-dev \
            qt5-qtscript-dev \
            qt5-qttools-dev \
            qt5-qtsvg-dev \
            git \
            build-base \
            pkgconf \
            sudo \
            cmake \
            alpine-sdk

      - name: Create user
        run: |
          adduser -D builduser
          echo "builduser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Clone DIE-engine
        run: |
          git clone --recursive https://github.com/horsicq/DIE-engine.git /home/builduser/DIE-engine
          chown -R builduser:builduser /home/builduser/DIE-engine

      - name: Build
        run: |
          sudo -u builduser sh -c '
          pwd
          cd /home/builduser/DIE-engine
          pwd
          chmod +x build_alpinepkg.sh
          ./build_alpinepkg.sh
          '

      - name: Verify APK
        run: |
          if ! ls /home/builduser/DIE-engine/release/*.apk >/dev/null 2>&1; then
            echo "APK file does not exist"
            exit 1
          fi

          ls -lah /home/builduser/DIE-engine/release/

      - name: Upload Release APK
        uses: softprops/action-gh-release@v3
        with:
          tag_name: Beta
          draft: false
          prerelease: true
          files: |
            ${{ github.workspace }}\DIE-engine/release\*.apk
