name: Build with Qt 5.6.3

on: [push, pull_request]

jobs:
  build:
    name: Build VS 2017, Windows XP
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
