name: Kali Linux CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kalilinux:
    runs-on: ubuntu-latest
    container:
      image: kalilinux/kali-rolling
    steps:
      - name: Install dependencies
        run: |
          apt-get update -y
          
          apt-get install -y git qtbase5-dev qtscript5-dev qttools5-dev qttools5-dev-tools libqt5svg5-dev build-essential cmake

      - name: Checkout Repository
        run:
          git clone https://github.com/horsicq/DIE-engine --recursive
          cd build

      - name: Build
        working-directory: ${{ github.workspace }}
        shell: bash
        run: |
          bash -ex build_dpkg.sh
          
          for file in release/die_*_linux_amd64.deb; do
            if [ -f "$file" ]; then
              mv "$file" "${file/_linux_/_kalilinux_}"
            fi
          done

      - name: Upload Release as Download
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Beta
          draft: false
          prerelease: true
          files: |
            ${{ github.workspace }}/release/*.deb