name: macOS CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-osx:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          host: mac
          target: desktop
          arch: clang_64
          modules: qtscript

      - name: Fix Qt path for build_mac.sh
        run: |
          REAL_QMAKE=$(find $HOME -name qmake | grep clang_64 | head -n 1)
          echo "Found qmake: $REAL_QMAKE"
          REAL_QT=$(dirname $(dirname $REAL_QMAKE))
          mkdir -p /Users/runner/Qt/5.15.2
          ln -s $REAL_QT /Users/runner/Qt/5.15.2/clang_64
          ls -la /Users/runner/Qt/5.15.2/clang_64/bin/qmake

      - name: Build DiE macOS
        run: |
          rsync -av --exclude 'DIE-engine' ./ DIE-engine/
          cd DIE-engine
          chmod +x build_mac.sh
          ./build_mac.sh

      - name: Upload macOS Release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Beta
          draft: false
          prerelease: true
          files: |
            /Users/runner/work/*/*/DIE-engine/release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}