name: macOS CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-osx:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          host: mac
          target: desktop
          arch: clang_64
          modules: qtscript

      - name: Clone DIE-engine
        run: |
          git clone https://github.com/horsicq/DIE-engine.git --recursive

      - name: Build DiE macOS
        run: |
          cd DIE-engine
          chmod a+x build_mac.sh
          ./build_mac.sh

      - name: Upload macOS Release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Beta
          draft: false
          prerelease: true
          files: |
            /Users/runner/work/*/*/DIE-engine/release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}