name: ParrotOS CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-parrotos:
    runs-on: ubuntu-latest
    container:
      image: parrotsec/core:rolling
    steps:
      - name: Install dependencies
        run: |
          echo "deb [trusted=yes] https://deb.parrot.sh/parrot parrot main contrib non-free" > /etc/apt/sources.list.d/parrot.list
          
          apt-get update -y
          
          apt-get install -y parrot-archive-keyring || true

          apt update -y
          
          apt-get install git qtbase5-dev qtscript5-dev qttools5-dev-tools libqt5svg5-dev build-essential cmake -y

      - name: Clone Repository
        run: |
          git clone https://github.com/horsicq/DIE-engine.git --recursive

      - name: Build
        working-directory: ${{ github.workspace }}/DIE-engine
        run: |
          bash -ex build_dpkg.sh

      - name: Upload Release as Download
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Beta
          draft: false
          prerelease: true
          files: |
            ${{ github.workspace }}/DIE-engine/release/*.deb