name: Build DIE-engine (Ubuntu RISC-V64 Qt5)

on:
  workflow_dispatch:

jobs:
  build-riscv64:

    runs-on: ubuntu-latest

    steps:
      - name: Enable QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Clone DIE-engine
        run: |
          git clone --recursive \
            https://github.com/horsicq/DIE-engine.git

      - name: Build on Ubuntu riscv64
        run: |
          docker run \
            --rm \
            --platform linux/riscv64 \
            -v "$PWD/DIE-engine:/src" \
            ubuntu:22.04 \
            bash -c '
              set -ex

              apt update

             apt-get install qtbase5-dev qtscript5-dev qttools5-dev-tools libqt5svg5-dev git build-essential qtchooser qt5-qmake -y


              cd /src

              cmake \
                -B build \
                -G Ninja \
                -DCMAKE_BUILD_TYPE=Release

              cmake \
                --build build \
                --parallel 2
            '

      - name: Package result
        run: |
          mkdir -p release

          tar \
            -czf \
            release/detect-it-easy-4.0.0-linux-riscv64.tar.gz \
            -C DIE-engine \
            build

          ls -lh release

      - name: Upload Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: Beta
          draft: false
          prerelease: true
          files: |
            release/*.tar.gz